// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: file.sql

package repository

import (
	"context"
	"time"
)

const createFile = `-- name: CreateFile :one
insert into files (name, original_name, content_type, md5) values ($1, $2, $3, $4) returning id, name, original_name, content_type, md5, created_at, deleted_at
`

type CreateFileParams struct {
	Name         string `json:"name"`
	OriginalName string `json:"original_name"`
	ContentType  string `json:"content_type"`
	Md5          string `json:"md5"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Name,
		arg.OriginalName,
		arg.ContentType,
		arg.Md5,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteFileById = `-- name: DeleteFileById :exec
update files set deleted_at = now() where id = $1
`

func (q *Queries) DeleteFileById(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFileById, id)
	return err
}

const deleteFileByNanoId = `-- name: DeleteFileByNanoId :exec
delete from files where name = $1
`

func (q *Queries) DeleteFileByNanoId(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteFileByNanoId, name)
	return err
}

const getAllFiles = `-- name: GetAllFiles :many
select id, name, original_name, content_type, md5, created_at, deleted_at from files
`

func (q *Queries) GetAllFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getAllFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginalName,
			&i.ContentType,
			&i.Md5,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
select id, name, original_name, content_type, md5, created_at, deleted_at from files where id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileByName = `-- name: GetFileByName :one
select id, name, original_name, content_type, md5, created_at, deleted_at from files where name = $1
`

func (q *Queries) GetFileByName(ctx context.Context, name string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByName, name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileIdByNanoId = `-- name: GetFileIdByNanoId :one
select id, name, original_name, content_type, md5, created_at, deleted_at from files where name = $1
`

func (q *Queries) GetFileIdByNanoId(ctx context.Context, name string) (File, error) {
	row := q.db.QueryRow(ctx, getFileIdByNanoId, name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileIdsFromUserStore = `-- name: GetFileIdsFromUserStore :many
SELECT f.id AS file_id
FROM files f
JOIN file_store fs ON f.id = fs.fileId
JOIN user_store us ON fs.storeId = us.storeId
WHERE us.storeId = $1 and us.userId = $2
`

type GetFileIdsFromUserStoreParams struct {
	Storeid int32 `json:"storeid"`
	Userid  int32 `json:"userid"`
}

func (q *Queries) GetFileIdsFromUserStore(ctx context.Context, arg GetFileIdsFromUserStoreParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getFileIdsFromUserStore, arg.Storeid, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var file_id int32
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileOriginalNameByNanoId = `-- name: GetFileOriginalNameByNanoId :one
select id, name, original_name, content_type, md5, created_at, deleted_at from files where name = $1
`

func (q *Queries) GetFileOriginalNameByNanoId(ctx context.Context, name string) (File, error) {
	row := q.db.QueryRow(ctx, getFileOriginalNameByNanoId, name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFilesPaginated = `-- name: GetFilesPaginated :many
SELECT 
    f.id AS file_id,
    f.name AS file_name,
    f.original_name AS file_original_name,
    f.content_type AS file_content_type,
    f.md5 AS file_md5,
    f.created_at AS file_created_at
FROM 
    users u
JOIN 
    user_store us ON u.id = us.userId
JOIN 
    stores s ON us.storeId = s.id
JOIN 
    file_store fs ON s.id = fs.storeId
JOIN 
    files f ON fs.fileId = f.id
WHERE 
    u.id = $3
AND 
    s.id = $4
AND
    f.deleted_at IS NULL
ORDER BY 
    f.created_at DESC
LIMIT $1 OFFSET $2
`

type GetFilesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
	ID     int32 `json:"id"`
	ID_2   int32 `json:"id_2"`
}

type GetFilesPaginatedRow struct {
	FileID           int32     `json:"file_id"`
	FileName         string    `json:"file_name"`
	FileOriginalName string    `json:"file_original_name"`
	FileContentType  string    `json:"file_content_type"`
	FileMd5          string    `json:"file_md5"`
	FileCreatedAt    time.Time `json:"file_created_at"`
}

func (q *Queries) GetFilesPaginated(ctx context.Context, arg GetFilesPaginatedParams) ([]GetFilesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getFilesPaginated,
		arg.Limit,
		arg.Offset,
		arg.ID,
		arg.ID_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesPaginatedRow
	for rows.Next() {
		var i GetFilesPaginatedRow
		if err := rows.Scan(
			&i.FileID,
			&i.FileName,
			&i.FileOriginalName,
			&i.FileContentType,
			&i.FileMd5,
			&i.FileCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOwner = `-- name: IsOwner :one
SELECT EXISTS (
    SELECT 1
    FROM users u
    JOIN user_store us ON u.id = us.userId
    JOIN stores s ON us.storeId = s.id
    JOIN file_store fs ON s.id = fs.storeId
    JOIN files f ON fs.fileId = f.id
    WHERE u.username = $1 AND f.name = $2 
)
`

type IsOwnerParams struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}

func (q *Queries) IsOwner(ctx context.Context, arg IsOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOwner, arg.Username, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const renameFile = `-- name: RenameFile :one
update files set name = $2 where id = $1 returning id, name, original_name, content_type, md5, created_at, deleted_at
`

type RenameFileParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRow(ctx, renameFile, arg.ID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OriginalName,
		&i.ContentType,
		&i.Md5,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
