// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	OriginalName string           `json:"original_name"`
	ContentType  string           `json:"content_type"`
	Md5          string           `json:"md5"`
	CreatedAt    time.Time        `json:"created_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type FileStore struct {
	ID      int32 `json:"id"`
	Fileid  int32 `json:"fileid"`
	Storeid int32 `json:"storeid"`
}

type Store struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Cover     int32     `json:"cover"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserStore struct {
	ID      int32 `json:"id"`
	Userid  int32 `json:"userid"`
	Storeid int32 `json:"storeid"`
}
