// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type File struct {
	ID           int64      `json:"id"`
	Name         string     `json:"name"`
	OriginalName string     `json:"original_name"`
	ContentType  string     `json:"content_type"`
	Md5          string     `json:"md5"`
	CreatedAt    *time.Time `json:"created_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type FileStore struct {
	ID      int64 `json:"id"`
	Fileid  int64 `json:"fileid"`
	Storeid int64 `json:"storeid"`
}

type Store struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Cover     int64      `json:"cover"`
	CreatedAt *time.Time `json:"created_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserStore struct {
	ID      int64 `json:"id"`
	Userid  int64 `json:"userid"`
	Storeid int64 `json:"storeid"`
}
