// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_store.sql

package repository

import (
	"context"
)

const addStoreToUser = `-- name: AddStoreToUser :exec
insert into user_store (userId, storeId) values ($1, $2)
`

type AddStoreToUserParams struct {
	Userid  int32 `json:"userid"`
	Storeid int32 `json:"storeid"`
}

func (q *Queries) AddStoreToUser(ctx context.Context, arg AddStoreToUserParams) error {
	_, err := q.db.Exec(ctx, addStoreToUser, arg.Userid, arg.Storeid)
	return err
}

const calculatePages = `-- name: CalculatePages :one
SELECT CEIL(COUNT(fs.fileId)::float / $1) AS total_pages
FROM file_store fs
JOIN user_store us ON fs.storeId = us.storeId
WHERE us.userId = $2 AND fs.storeId = $3
`

type CalculatePagesParams struct {
	Fileid  int32 `json:"fileid"`
	Userid  int32 `json:"userid"`
	Storeid int32 `json:"storeid"`
}

func (q *Queries) CalculatePages(ctx context.Context, arg CalculatePagesParams) (float64, error) {
	row := q.db.QueryRow(ctx, calculatePages, arg.Fileid, arg.Userid, arg.Storeid)
	var total_pages float64
	err := row.Scan(&total_pages)
	return total_pages, err
}

const getUserStores = `-- name: GetUserStores :many
select id, userid, storeid from user_store where userId = $1
`

func (q *Queries) GetUserStores(ctx context.Context, userid int32) ([]UserStore, error) {
	rows, err := q.db.Query(ctx, getUserStores, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserStore
	for rows.Next() {
		var i UserStore
		if err := rows.Scan(&i.ID, &i.Userid, &i.Storeid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStoreFromUser = `-- name: RemoveStoreFromUser :exec
delete from user_store where userId = $1 and storeId = $2
`

type RemoveStoreFromUserParams struct {
	Userid  int32 `json:"userid"`
	Storeid int32 `json:"storeid"`
}

func (q *Queries) RemoveStoreFromUser(ctx context.Context, arg RemoveStoreFromUserParams) error {
	_, err := q.db.Exec(ctx, removeStoreFromUser, arg.Userid, arg.Storeid)
	return err
}
